---
production: &default
  serverPort: 3000
  baseUrl: http://www.traffcit.io
  views:
    engine: .hbs
    extension: .hbs
    layout: dashboard
  html:
    livereload: false
    minify: true
    css:
      lessPrecompile: true
      compress: true
  languages:
    default: en
    list: [en, es]
  security:
    secret: tr4ffcit.com
  session:
    cookieDomain: .traffcit.com
    maxAge: 259200
    cookiePrefix: 'mdSession_'
    path: '/'
    httpOnly: true

stage: &stage
  <<: *default
  baseUrl: http://stage.trafcity.io

latest: &latest
  <<: *stage
  baseUrl: http://latest.trafcity.io

development:
  <<: *latest
  baseUrl: http://local.trafcity.io
  html:
    livereload: true
    minify: false
    lessPrecompile: false
    compress: false
